
import http from 'k6/http';
import { sleep } from 'k6';

const url = 'https://model.cloudnative.computer/v1/completions';
const model = 'deepseek-r1-distill-llama-8b';
const prompts = [
  "How does Python programming work?",
  "How can I learn more about neural networks?",
  "What is the history of cloud computing?",
  "What is the history of Python programming?",
  "How can I learn more about music theory?",
  "Give me a summary of AI.",
  "Write a story about a the stock market.",
  "Explain the concept of cooking.",
  "How does blockchain work?",
  "Why is golang important?",
  "What is the history of Python programming?",
  "Explain the concept of AI.",
  "Explain the concept of artificial general intelligence.",
  "How can I learn more about philosophy?",
  "Tell me a joke about neural networks.",
  "How does Python programming work?",
  "Explain the concept of artificial general intelligence.",
  "How can I learn more about AI?",
  "How can I learn more about cybersecurity?",
  "What is the history of neural networks?",
  "What are the benefits of cybersecurity?",
  "What is the history of space travel?",
  "How does blockchain work?",
  "How does blockchain work?",
  "Why is machine learning important?",
  "How does artificial general intelligence work?",
  "Compare quantum mechanics and blockchain.",
  "How can I learn more about Shakespeare?",
  "Write a story about a climate change.",
  "Give me a summary of Docker.",
  "Give me a summary of neural networks.",
  "Write a story about a medieval history.",
  "Why is Python programming important?",
  "Explain the concept of artificial general intelligence.",
  "How does football work?",
  "Write a story about a the stock market.",
  "Explain the concept of climate change.",
  "Give me a summary of cooking.",
  "Explain the concept of quantum mechanics.",
  "Give me a summary of space travel.",
  "What are the benefits of fitness?",
  "Write a story about a artificial general intelligence.",
  "How can I learn more about philosophy?",
  "Give me a summary of fitness.",
  "Write a story about a Docker.",
  "Explain the concept of cybersecurity.",
  "How does nutrition work?",
  "Tell me a joke about music theory.",
  "Why is social media important?",
  "How can I learn more about social media?",
  "Tell me a joke about machine learning.",
  "Compare the stock market and golang.",
  "What are the benefits of cloud computing?",
  "What is the history of cybersecurity?",
  "Explain the concept of Docker.",
  "Give me a summary of cloud computing.",
  "What are the benefits of the stock market?",
  "What is the history of music theory?",
  "Why is philosophy important?",
  "How does football work?",
  "Explain the concept of AI.",
  "Compare football and medieval history.",
  "Explain the concept of machine learning.",
  "Explain the concept of Shakespeare.",
  "Give me a summary of quantum mechanics.",
  "Give me a summary of Kubernetes.",
  "Give me a summary of quantum mechanics.",
  "How can I learn more about cloud computing?",
  "What is the history of football?",
  "How can I learn more about Shakespeare?",
  "Write a story about a Python programming.",
  "How can I learn more about Docker?",
  "Write a story about a Kubernetes.",
  "Tell me a joke about football.",
  "Explain the concept of Kubernetes.",
  "Explain the concept of Python programming.",
  "What are the benefits of Shakespeare?",
  "Why is neural networks important?",
  "What is the history of blockchain?",
  "What are the benefits of Python programming?",
  "Tell me a joke about cloud computing.",
  "What is the history of machine learning?",
  "Tell me a joke about AI.",
  "Why is the stock market important?",
  "Why is Python programming important?",
  "Why is neural networks important?",
  "Tell me a joke about Docker.",
  "What is the history of Docker?",
  "How does Kubernetes work?",
  "Write a story about a artificial general intelligence.",
  "How does cooking work?",
  "Give me a summary of fitness.",
  "How does music theory work?",
  "What is the history of Python programming?",
  "Give me a summary of Python programming.",
  "Write a story about a machine learning.",
  "How does fitness work?",
  "Explain the concept of nutrition.",
  "Explain the concept of music theory.",
  "Why is cybersecurity important?",
  "Give me a summary of nutrition.",
  "Compare Shakespeare and fitness.",
  "Compare Shakespeare and quantum mechanics.",
  "How can I learn more about football?",
  "Write a story about a philosophy.",
  "Give me a summary of climate change.",
  "Compare Kubernetes and AI.",
  "Write a story about a blockchain.",
  "Why is machine learning important?",
  "Write a story about a space travel.",
  "Compare AI and nutrition.",
  "Why is Python programming important?",
  "Compare AI and blockchain.",
  "Compare neural networks and AI.",
  "How does blockchain work?",
  "Tell me a joke about machine learning.",
  "Write a story about a cybersecurity.",
  "Explain the concept of fitness.",
  "How does medieval history work?",
  "Compare medieval history and nutrition.",
  "What are the benefits of data privacy?",
  "What is the history of football?",
  "What is the history of artificial general intelligence?",
  "Compare football and machine learning.",
  "Compare blockchain and climate change.",
  "Compare Python programming and blockchain.",
  "How does Shakespeare work?",
  "Tell me a joke about data privacy.",
  "Tell me a joke about AI.",
  "Tell me a joke about space travel.",
  "Give me a summary of music theory.",
  "Explain the concept of fitness.",
  "Tell me a joke about climate change.",
  "How does medieval history work?",
  "Give me a summary of Python programming.",
  "Tell me a joke about golang.",
  "Tell me a joke about social media.",
  "Tell me a joke about AI.",
  "What are the benefits of philosophy?",
  "How does machine learning work?",
  "Tell me a joke about Shakespeare.",
  "Give me a summary of blockchain.",
  "What are the benefits of fitness?",
  "Give me a summary of cloud computing.",
  "Tell me a joke about Shakespeare.",
  "Why is music theory important?",
  "Why is AI important?",
  "Give me a summary of machine learning.",
  "What are the benefits of Shakespeare?",
  "What are the benefits of social media?",
  "How can I learn more about blockchain?",
  "What are the benefits of medieval history?",
  "Tell me a joke about Python programming.",
  "How does climate change work?",
  "Compare nutrition and AI.",
  "Tell me a joke about machine learning.",
  "Explain the concept of Kubernetes.",
  "Write a story about a AI.",
  "Why is neural networks important?",
  "How does nutrition work?",
  "Why is AI important?",
  "Give me a summary of data privacy.",
  "What are the benefits of social media?",
  "What is the history of AI?",
  "Give me a summary of climate change.",
  "Compare medieval history and data privacy.",
  "What are the benefits of fitness?",
  "Tell me a joke about nutrition.",
  "Write a story about a Python programming.",
  "Give me a summary of AI.",
  "How can I learn more about machine learning?",
  "Explain the concept of machine learning.",
  "Compare data privacy and cybersecurity.",
  "How can I learn more about cloud computing?",
  "Compare space travel and climate change.",
  "Tell me a joke about medieval history.",
  "How can I learn more about philosophy?",
  "How does Kubernetes work?",
  "Give me a summary of the stock market.",
  "Give me a summary of cooking.",
  "Write a story about a cooking.",
  "Give me a summary of data privacy.",
  "Why is golang important?",
  "Tell me a joke about data privacy.",
  "Write a story about a cybersecurity.",
  "Give me a summary of Kubernetes.",
  "What are the benefits of cooking?",
  "Give me a summary of Shakespeare.",
  "How does Python programming work?",
  "Compare artificial general intelligence and social media.",
  "How does Python programming work?",
  "How can I learn more about quantum mechanics?",
  "What is the history of cybersecurity?",
  "Compare nutrition and cloud computing.",
  "Explain the concept of Shakespeare.",
  "Why is artificial general intelligence important?",
  "What are the benefits of golang?",
  "What is the history of machine learning?",
  "Tell me a joke about football.",
  "What is the history of social media?",
  "Compare music theory and philosophy.",
  "What are the benefits of music theory?",
  "Give me a summary of Python programming.",
  "How can I learn more about philosophy?",
  "What are the benefits of Shakespeare?",
  "Compare blockchain and Docker.",
  "How does artificial general intelligence work?",
  "Explain the concept of AI.",
  "Tell me a joke about fitness.",
  "Write a story about a space travel.",
  "Why is Kubernetes important?",
  "Explain the concept of philosophy.",
  "Tell me a joke about fitness.",
  "How can I learn more about music theory?",
  "Write a story about a Shakespeare.",
  "Explain the concept of Kubernetes.",
  "How can I learn more about Shakespeare?",
  "Give me a summary of football.",
  "How does the stock market work?",
  "What are the benefits of quantum mechanics?",
  "Write a story about a golang.",
  "Compare golang and Shakespeare.",
  "Tell me a joke about machine learning.",
  "Write a story about a nutrition.",
  "Why is golang important?",
  "How can I learn more about Python programming?",
  "What are the benefits of machine learning?",
  "Tell me a joke about medieval history.",
  "Write a story about a nutrition.",
  "How does Kubernetes work?",
  "How does medieval history work?",
  "Write a story about a Kubernetes.",
  "Write a story about a music theory.",
  "Give me a summary of AI.",
  "What is the history of Shakespeare?",
  "Tell me a joke about social media.",
  "Compare social media and music theory.",
  "Why is philosophy important?",
  "What are the benefits of philosophy?",
  "What is the history of machine learning?",
  "Compare fitness and quantum mechanics.",
  "How can I learn more about space travel?",
  "Write a story about a music theory.",
  "Write a story about a artificial general intelligence.",
  "What is the history of Kubernetes?",
  "Give me a summary of music theory.",
  "What are the benefits of artificial general intelligence?",
  "Tell me a joke about cybersecurity.",
  "Explain the concept of philosophy.",
  "What is the history of Docker?",
  "What are the benefits of AI?",
  "What are the benefits of philosophy?",
  "Write a story about a blockchain.",
  "Why is artificial general intelligence important?",
  "How can I learn more about football?",
  "Tell me a joke about football.",
  "Why is quantum mechanics important?",
  "How can I learn more about Python programming?",
  "Why is quantum mechanics important?",
  "What is the history of medieval history?",
  "How does Python programming work?",
  "What is the history of cloud computing?",
  "How does golang work?",
  "What is the history of cybersecurity?",
  "Tell me a joke about the stock market.",
  "How does cloud computing work?",
  "Compare AI and the stock market.",
  "How does Shakespeare work?",
  "What is the history of football?",
  "Explain the concept of music theory.",
  "Tell me a joke about the stock market.",
  "Give me a summary of medieval history.",
  "What is the history of blockchain?",
  "Explain the concept of space travel.",
  "What are the benefits of climate change?",
  "Compare data privacy and AI.",
  "Explain the concept of the stock market.",
  "What is the history of fitness?",
  "Give me a summary of Docker.",
  "How does the stock market work?",
  "Why is blockchain important?",
  "Compare the stock market and neural networks.",
  "How does fitness work?",
  "Explain the concept of cybersecurity.",
  "Write a story about a climate change.",
  "Why is AI important?",
  "Why is Shakespeare important?",
  "How does machine learning work?",
  "Why is cybersecurity important?",
  "What are the benefits of social media?",
  "Write a story about a philosophy.",
  "Why is climate change important?",
  "Tell me a joke about Docker.",
  "What are the benefits of medieval history?",
  "Explain the concept of Docker.",
  "Give me a summary of blockchain.",
  "Tell me a joke about cooking.",
  "Why is nutrition important?",
  "Compare cloud computing and football.",
  "Write a story about a philosophy.",
  "Tell me a joke about fitness.",
  "What is the history of fitness?",
  "How can I learn more about blockchain?",
  "What is the history of quantum mechanics?",
  "How does Python programming work?",
  "How can I learn more about climate change?",
  "How can I learn more about football?",
  "Give me a summary of Python programming.",
  "Give me a summary of golang.",
  "Give me a summary of social media.",
  "How does cooking work?",
  "Give me a summary of space travel.",
  "What is the history of fitness?",
  "What are the benefits of climate change?",
  "Why is Docker important?",
  "Compare Python programming and space travel.",
  "How does blockchain work?",
  "What are the benefits of Python programming?",
  "Explain the concept of football.",
  "Compare climate change and music theory.",
  "How can I learn more about Python programming?",
  "What is the history of data privacy?",
  "How can I learn more about cybersecurity?",
  "What are the benefits of Docker?",
  "How does machine learning work?",
  "How does machine learning work?",
  "Give me a summary of climate change.",
  "Write a story about a cooking.",
  "Explain the concept of machine learning.",
  "Compare quantum mechanics and the stock market.",
  "What is the history of Python programming?",
  "Why is philosophy important?",
  "Explain the concept of cloud computing.",
  "Explain the concept of music theory.",
  "What are the benefits of Python programming?",
  "Explain the concept of Docker.",
  "Tell me a joke about social media.",
  "Tell me a joke about cloud computing.",
  "Why is climate change important?",
  "Explain the concept of neural networks.",
  "Explain the concept of cybersecurity.",
  "What are the benefits of cybersecurity?",
  "What is the history of AI?",
  "Write a story about a neural networks.",
  "How does data privacy work?",
  "Write a story about a cooking.",
  "Write a story about a social media.",
  "Write a story about a Docker.",
  "Tell me a joke about nutrition.",
  "How can I learn more about Shakespeare?",
  "What is the history of data privacy?",
  "Tell me a joke about quantum mechanics.",
  "Why is Python programming important?",
  "Explain the concept of blockchain.",
  "Why is Kubernetes important?",
  "Compare cooking and Kubernetes.",
  "Explain the concept of music theory.",
  "How can I learn more about medieval history?",
  "What is the history of medieval history?",
  "What is the history of cybersecurity?",
  "How can I learn more about social media?",
  "Compare golang and Shakespeare.",
  "Explain the concept of music theory.",
  "What is the history of music theory?",
  "Why is music theory important?",
  "Write a story about a space travel.",
  "Write a story about a climate change.",
  "Compare music theory and artificial general intelligence.",
  "Why is Kubernetes important?",
  "Tell me a joke about fitness.",
  "Explain the concept of AI.",
  "What are the benefits of fitness?",
  "Write a story about a golang.",
  "What are the benefits of cybersecurity?",
  "What are the benefits of medieval history?",
  "Why is data privacy important?",
  "Compare the stock market and data privacy.",
  "How can I learn more about Docker?",
  "How can I learn more about music theory?",
  "What is the history of social media?",
  "What are the benefits of the stock market?",
  "What are the benefits of AI?",
  "How does Kubernetes work?",
  "Give me a summary of data privacy.",
  "Why is cooking important?",
  "How does Python programming work?",
  "How can I learn more about blockchain?",
  "Write a story about a the stock market.",
  "How can I learn more about golang?",
  "Tell me a joke about cybersecurity.",
  "How can I learn more about cloud computing?",
  "Explain the concept of Shakespeare.",
  "Explain the concept of climate change.",
  "Compare artificial general intelligence and blockchain.",
  "Write a story about a social media.",
  "What are the benefits of Shakespeare?",
  "Explain the concept of AI.",
  "What is the history of cloud computing?",
  "Tell me a joke about data privacy.",
  "Tell me a joke about cybersecurity.",
  "What is the history of football?",
  "What is the history of football?",
  "How can I learn more about football?",
  "Tell me a joke about cooking.",
  "What are the benefits of quantum mechanics?",
  "How can I learn more about quantum mechanics?",
  "How does data privacy work?",
  "What are the benefits of medieval history?",
  "Explain the concept of neural networks.",
  "Give me a summary of cloud computing.",
  "Why is climate change important?",
  "Write a story about a social media.",
  "Give me a summary of machine learning.",
  "Write a story about a AI.",
  "How can I learn more about machine learning?",
  "How does the stock market work?",
  "Tell me a joke about climate change.",
  "Explain the concept of football.",
  "Give me a summary of Python programming.",
  "Why is space travel important?",
  "Tell me a joke about Python programming.",
  "Tell me a joke about climate change.",
  "Write a story about a the stock market.",
  "What are the benefits of football?",
  "Compare AI and data privacy.",
  "Why is blockchain important?",
  "How can I learn more about Docker?",
  "How does nutrition work?",
  "Explain the concept of social media.",
  "How can I learn more about philosophy?",
  "How does data privacy work?",
  "Tell me a joke about philosophy.",
  "How can I learn more about machine learning?",
  "Explain the concept of Docker.",
  "What are the benefits of data privacy?",
  "Explain the concept of artificial general intelligence.",
  "Compare Docker and artificial general intelligence.",
  "What are the benefits of social media?",
  "Compare cloud computing and football.",
  "Why is cybersecurity important?",
  "Tell me a joke about football.",
  "Compare space travel and artificial general intelligence.",
  "Compare artificial general intelligence and neural networks.",
  "What are the benefits of Kubernetes?",
  "Explain the concept of Kubernetes.",
  "What is the history of neural networks?",
  "Give me a summary of machine learning.",
  "How does climate change work?",
  "How can I learn more about cybersecurity?",
  "How does Docker work?",
  "Why is cybersecurity important?",
  "Why is blockchain important?",
  "Why is climate change important?",
  "Give me a summary of space travel.",
  "What is the history of cloud computing?",
  "What is the history of blockchain?",
  "Explain the concept of data privacy.",
  "Explain the concept of climate change.",
  "What is the history of fitness?",
  "What is the history of cloud computing?",
  "How can I learn more about Kubernetes?",
  "Compare social media and quantum mechanics.",
  "Compare philosophy and space travel.",
  "What is the history of philosophy?",
  "Give me a summary of cybersecurity.",
  "What is the history of cloud computing?",
  "How can I learn more about quantum mechanics?",
  "Give me a summary of Python programming.",
  "How does blockchain work?",
  "Give me a summary of cooking.",
  "Why is football important?",
  "What is the history of data privacy?",
  "Why is cloud computing important?",
  "Why is cloud computing important?",
  "Give me a summary of artificial general intelligence.",
  "Why is Python programming important?",
  "Tell me a joke about Docker.",
  "What are the benefits of climate change?",
  "What is the history of neural networks?",
  "Explain the concept of Kubernetes.",
  "How can I learn more about cybersecurity?",
  "What is the history of fitness?",
  "Write a story about a Shakespeare.",
  "Why is artificial general intelligence important?",
  "How does philosophy work?",
  "Why is Shakespeare important?",
  "Tell me a joke about Python programming.",
  "How does music theory work?",
  "Tell me a joke about cooking.",
  "Compare fitness and social media.",
  "Compare nutrition and cooking.",
  "Tell me a joke about nutrition.",
  "What are the benefits of machine learning?",
  "What are the benefits of nutrition?",
  "Give me a summary of climate change.",
  "Why is the stock market important?",
  "Why is football important?",
  "How does Docker work?",
  "Write a story about a space travel.",
  "Tell me a joke about quantum mechanics.",
  "Explain the concept of the stock market.",
  "Compare music theory and neural networks.",
  "How can I learn more about social media?",
  "Compare football and climate change.",
  "What are the benefits of cloud computing?",
  "Write a story about a social media.",
  "Why is data privacy important?",
  "Write a story about a AI.",
  "Write a story about a quantum mechanics.",
  "Tell me a joke about blockchain.",
  "Explain the concept of blockchain.",
  "How can I learn more about social media?",
  "Give me a summary of football.",
  "How can I learn more about philosophy?",
  "What are the benefits of the stock market?",
  "Tell me a joke about golang.",
  "What is the history of artificial general intelligence?",
  "How can I learn more about the stock market?",
  "Tell me a joke about cloud computing.",
  "How can I learn more about quantum mechanics?",
  "How can I learn more about the stock market?",
  "How can I learn more about nutrition?",
  "Why is artificial general intelligence important?",
  "What are the benefits of golang?",
  "Write a story about a football.",
  "Compare cooking and Python programming.",
  "Tell me a joke about climate change.",
  "Compare cooking and Python programming.",
  "Explain the concept of AI.",
  "How can I learn more about the stock market?",
  "What are the benefits of cooking?",
  "Why is Kubernetes important?",
  "Tell me a joke about Docker.",
  "Give me a summary of football.",
  "What are the benefits of fitness?",
  "Compare cybersecurity and golang.",
  "Give me a summary of nutrition.",
  "Compare data privacy and football.",
  "Explain the concept of medieval history.",
  "Explain the concept of blockchain.",
  "Why is cloud computing important?",
  "Give me a summary of social media.",
  "How does cooking work?",
  "What are the benefits of cooking?",
  "Why is football important?",
  "What are the benefits of Python programming?",
  "How does nutrition work?",
  "Give me a summary of social media.",
  "How does music theory work?",
  "Why is football important?",
  "Compare blockchain and quantum mechanics.",
  "Tell me a joke about Python programming.",
  "Compare data privacy and space travel.",
  "Tell me a joke about football.",
  "Give me a summary of cloud computing.",
  "Give me a summary of Shakespeare.",
  "Why is football important?",
  "Why is fitness important?",
  "What is the history of AI?",
  "Write a story about a space travel.",
  "Explain the concept of philosophy.",
  "Give me a summary of machine learning.",
  "What are the benefits of neural networks?",
  "Write a story about a machine learning.",
  "Give me a summary of machine learning.",
  "Explain the concept of climate change.",
  "Tell me a joke about social media.",
  "Write a story about a cooking.",
  "Why is cooking important?",
  "Why is space travel important?",
  "Write a story about a Shakespeare.",
  "Explain the concept of machine learning.",
  "What are the benefits of neural networks?",
  "Explain the concept of football.",
  "Write a story about a medieval history.",
  "Why is space travel important?",
  "Explain the concept of Docker.",
  "Why is Shakespeare important?",
  "What are the benefits of music theory?",
  "Tell me a joke about fitness.",
  "How does data privacy work?",
  "How can I learn more about music theory?",
  "What is the history of social media?",
  "Give me a summary of cybersecurity.",
  "Explain the concept of social media.",
  "Explain the concept of AI.",
  "How does Kubernetes work?",
  "Explain the concept of Python programming.",
  "Give me a summary of the stock market.",
  "Why is Docker important?",
  "Tell me a joke about data privacy.",
  "How can I learn more about the stock market?",
  "Why is the stock market important?",
  "Tell me a joke about artificial general intelligence.",
  "What is the history of golang?",
  "Give me a summary of Docker.",
  "Why is Python programming important?",
  "Compare football and Docker.",
  "Write a story about a cybersecurity.",
  "What is the history of fitness?",
  "How does AI work?",
  "Tell me a joke about nutrition.",
  "Compare nutrition and Kubernetes.",
  "Write a story about a social media.",
  "How does music theory work?",
  "Give me a summary of neural networks.",
  "Give me a summary of artificial general intelligence.",
  "Compare AI and Kubernetes.",
  "What is the history of Shakespeare?",
  "What are the benefits of quantum mechanics?",
  "Why is cloud computing important?",
  "Explain the concept of music theory.",
  "How does Kubernetes work?",
  "Explain the concept of cooking.",
  "Explain the concept of machine learning.",
  "What is the history of cloud computing?",
  "What is the history of neural networks?",
  "Tell me a joke about Python programming.",
  "What are the benefits of climate change?",
  "Explain the concept of machine learning.",
  "How can I learn more about cooking?",
  "Tell me a joke about cooking.",
  "Explain the concept of AI.",
  "Why is Docker important?",
  "Why is artificial general intelligence important?",
  "How does social media work?",
  "Write a story about a the stock market.",
  "How does Shakespeare work?",
  "Compare golang and nutrition.",
  "How does fitness work?",
  "Write a story about a nutrition.",
  "What are the benefits of social media?",
  "Give me a summary of cybersecurity.",
  "Give me a summary of music theory.",
  "Give me a summary of medieval history.",
  "Compare medieval history and AI.",
  "Explain the concept of space travel.",
  "Write a story about a artificial general intelligence.",
  "Write a story about a philosophy.",
  "Compare Python programming and music theory.",
  "How can I learn more about medieval history?",
  "How can I learn more about artificial general intelligence?",
  "What are the benefits of the stock market?",
  "How can I learn more about Python programming?",
  "Compare medieval history and artificial general intelligence.",
  "How does cooking work?",
  "Explain the concept of fitness.",
  "Explain the concept of fitness.",
  "What are the benefits of philosophy?",
  "What are the benefits of football?",
  "Tell me a joke about social media.",
  "How does artificial general intelligence work?",
  "Compare cooking and Shakespeare.",
  "How can I learn more about machine learning?",
  "How can I learn more about medieval history?",
  "Compare machine learning and climate change.",
  "Give me a summary of Python programming.",
  "Compare golang and Shakespeare.",
  "Explain the concept of space travel.",
  "Compare climate change and nutrition.",
  "Give me a summary of artificial general intelligence.",
  "How can I learn more about AI?",
  "How can I learn more about Kubernetes?",
  "How can I learn more about cloud computing?",
  "Compare the stock market and AI.",
  "Write a story about a cybersecurity.",
  "Compare Python programming and nutrition.",
  "Give me a summary of golang.",
  "Why is social media important?",
  "What are the benefits of football?",
  "Compare AI and space travel.",
  "What is the history of Kubernetes?",
  "Explain the concept of the stock market.",
  "What is the history of Shakespeare?",
  "Explain the concept of machine learning.",
  "What are the benefits of AI?",
  "Give me a summary of artificial general intelligence.",
  "Why is nutrition important?",
  "Give me a summary of quantum mechanics.",
  "How can I learn more about AI?",
  "Why is space travel important?",
  "What are the benefits of social media?",
  "Tell me a joke about cooking.",
  "Tell me a joke about AI.",
  "Write a story about a Docker.",
  "Write a story about a blockchain.",
  "Compare machine learning and music theory.",
  "What are the benefits of Shakespeare?",
  "How can I learn more about Kubernetes?",
  "What is the history of neural networks?",
  "Tell me a joke about artificial general intelligence.",
  "What are the benefits of Shakespeare?",
  "Compare Kubernetes and the stock market.",
  "Tell me a joke about golang.",
  "How does golang work?",
  "Explain the concept of social media.",
  "Write a story about a social media.",
  "Explain the concept of cloud computing.",
  "What is the history of music theory?",
  "How does neural networks work?",
  "Compare neural networks and Python programming.",
  "Explain the concept of artificial general intelligence.",
  "Why is cybersecurity important?",
  "Explain the concept of climate change.",
  "Why is climate change important?",
  "Why is Kubernetes important?",
  "What are the benefits of fitness?",
  "Write a story about a philosophy.",
  "Explain the concept of Python programming.",
  "Give me a summary of climate change.",
  "Explain the concept of cloud computing.",
  "Tell me a joke about nutrition.",
  "Tell me a joke about the stock market.",
  "What is the history of artificial general intelligence?",
  "How does Docker work?",
  "Write a story about a golang.",
  "Write a story about a artificial general intelligence.",
  "Why is cloud computing important?",
  "Write a story about a blockchain.",
  "Why is climate change important?",
  "Compare cloud computing and blockchain.",
  "Write a story about a cooking.",
  "Compare social media and cloud computing.",
  "How does Kubernetes work?",
  "What are the benefits of quantum mechanics?",
  "How does fitness work?",
  "Write a story about a music theory.",
  "Compare cloud computing and AI.",
  "Explain the concept of the stock market.",
  "Compare Kubernetes and quantum mechanics.",
  "Why is cooking important?",
  "Why is quantum mechanics important?",
  "Compare data privacy and music theory.",
  "Compare the stock market and neural networks.",
  "Explain the concept of cybersecurity.",
  "What are the benefits of climate change?",
  "Why is cloud computing important?",
  "Give me a summary of data privacy.",
  "How does Docker work?",
  "Compare climate change and machine learning.",
  "How does medieval history work?",
  "How does music theory work?",
  "What are the benefits of quantum mechanics?",
  "Compare music theory and cooking.",
  "How does medieval history work?",
  "Explain the concept of cooking.",
  "How does music theory work?",
  "Compare philosophy and data privacy.",
  "Why is social media important?",
  "Give me a summary of Shakespeare.",
  "How does artificial general intelligence work?",
  "Why is machine learning important?",
  "How does blockchain work?",
  "Compare the stock market and blockchain.",
  "Tell me a joke about Python programming.",
  "How does fitness work?",
  "Write a story about a music theory.",
  "Tell me a joke about fitness.",
  "Compare quantum mechanics and data privacy.",
  "Tell me a joke about golang.",
  "What is the history of football?",
  "What is the history of Kubernetes?",
  "Tell me a joke about social media.",
  "Explain the concept of fitness.",
  "How does Docker work?",
  "What are the benefits of Python programming?",
  "Tell me a joke about nutrition.",
  "How can I learn more about Python programming?",
  "How does machine learning work?",
  "What is the history of blockchain?",
  "Compare music theory and machine learning.",
  "Give me a summary of social media.",
  "Explain the concept of Docker.",
  "Compare quantum mechanics and cooking.",
  "Write a story about a nutrition.",
  "Write a story about a quantum mechanics.",
  "Tell me a joke about fitness.",
  "Tell me a joke about space travel.",
  "Compare machine learning and golang.",
  "How does cooking work?",
  "Write a story about a nutrition.",
  "Give me a summary of cloud computing.",
  "Explain the concept of space travel.",
  "What are the benefits of social media?",
  "What are the benefits of cooking?",
  "Write a story about a AI.",
  "Why is blockchain important?",
  "Tell me a joke about golang.",
  "Why is medieval history important?",
  "What is the history of data privacy?",
  "What is the history of climate change?",
  "How does blockchain work?",
  "Give me a summary of artificial general intelligence.",
  "What are the benefits of climate change?",
  "Write a story about a social media.",
  "Why is the stock market important?",
  "How does quantum mechanics work?",
  "How can I learn more about artificial general intelligence?",
  "What are the benefits of data privacy?",
  "How does data privacy work?",
  "Why is the stock market important?",
  "Why is neural networks important?",
  "Tell me a joke about Kubernetes.",
  "Compare quantum mechanics and Python programming.",
  "Tell me a joke about machine learning.",
  "Compare social media and Python programming.",
  "How can I learn more about climate change?",
  "Give me a summary of artificial general intelligence.",
  "Tell me a joke about Docker.",
  "Explain the concept of Python programming.",
  "Tell me a joke about philosophy.",
  "Compare neural networks and football.",
  "Give me a summary of space travel.",
  "Tell me a joke about Shakespeare.",
  "Tell me a joke about AI.",
  "Give me a summary of cooking.",
  "What are the benefits of cloud computing?",
  "Tell me a joke about Docker.",
  "Write a story about a the stock market.",
  "What are the benefits of social media?",
  "What are the benefits of AI?",
  "Write a story about a AI.",
  "Compare neural networks and philosophy.",
  "Compare Shakespeare and philosophy.",
  "Compare Python programming and space travel.",
  "Tell me a joke about Kubernetes.",
  "Explain the concept of data privacy.",
  "Write a story about a music theory.",
  "How can I learn more about Shakespeare?",
  "Explain the concept of nutrition.",
  "What are the benefits of fitness?",
  "How does cybersecurity work?",
  "Explain the concept of climate change.",
  "Why is medieval history important?",
  "Give me a summary of neural networks.",
  "How does the stock market work?",
  "What is the history of climate change?",
  "How can I learn more about space travel?",
  "How does blockchain work?",
  "Give me a summary of Docker.",
  "Why is cybersecurity important?",
  "Give me a summary of cooking.",
  "Tell me a joke about the stock market.",
  "Explain the concept of nutrition.",
  "Why is machine learning important?",
  "Compare machine learning and quantum mechanics.",
  "Compare AI and music theory.",
  "What are the benefits of fitness?",
  "Why is space travel important?",
  "Why is philosophy important?",
  "Compare Kubernetes and football.",
  "What are the benefits of cooking?",
  "How does neural networks work?",
  "How does blockchain work?",
  "How does golang work?",
  "Explain the concept of artificial general intelligence.",
  "Why is the stock market important?",
  "How does Docker work?",
  "How does social media work?",
  "Write a story about a medieval history.",
  "Write a story about a data privacy.",
  "How can I learn more about nutrition?",
  "What are the benefits of Shakespeare?",
  "Give me a summary of cloud computing.",
  "How can I learn more about football?",
  "What are the benefits of music theory?",
  "Write a story about a social media.",
  "How does space travel work?",
  "Write a story about a Kubernetes.",
  "What are the benefits of medieval history?",
  "What are the benefits of Shakespeare?",
  "Explain the concept of music theory.",
  "What are the benefits of social media?",
  "Give me a summary of neural networks.",
  "Explain the concept of Shakespeare.",
  "How does philosophy work?",
  "Give me a summary of social media.",
  "How does medieval history work?",
  "Give me a summary of space travel.",
  "Write a story about a Shakespeare.",
  "How does nutrition work?",
  "What are the benefits of golang?",
  "Why is AI important?",
  "Tell me a joke about social media.",
  "Why is Docker important?",
  "Compare cooking and football.",
  "What is the history of quantum mechanics?",
  "Compare Python programming and artificial general intelligence.",
  "What is the history of fitness?",
  "Tell me a joke about philosophy.",
  "What is the history of artificial general intelligence?",
  "Tell me a joke about philosophy.",
  "What are the benefits of football?",
  "What are the benefits of Shakespeare?",
  "Give me a summary of climate change.",
  "Tell me a joke about AI.",
  "Write a story about a cooking.",
  "Write a story about a cloud computing.",
  "How does climate change work?",
  "Why is Shakespeare important?",
  "Give me a summary of nutrition.",
  "Write a story about a the stock market.",
  "Write a story about a the stock market.",
  "Write a story about a cybersecurity.",
  "What is the history of Shakespeare?",
  "What is the history of medieval history?",
  "Explain the concept of space travel.",
  "Explain the concept of cloud computing.",
  "Compare climate change and football.",
  "How can I learn more about social media?",
  "Why is artificial general intelligence important?",
  "Give me a summary of climate change.",
  "Why is quantum mechanics important?",
  "Compare blockchain and cooking.",
  "Tell me a joke about fitness.",
  "How does golang work?",
  "What are the benefits of Python programming?",
  "Give me a summary of AI.",
  "Compare machine learning and golang.",
  "What are the benefits of nutrition?",
  "Why is social media important?",
  "How does space travel work?",
  "Write a story about a space travel.",
  "What is the history of neural networks?",
  "Why is Docker important?",
  "What is the history of cloud computing?",
  "Explain the concept of machine learning.",
  "Compare Docker and the stock market.",
  "Explain the concept of golang.",
  "Why is fitness important?",
  "Write a story about a blockchain.",
  "Tell me a joke about Shakespeare.",
  "Explain the concept of medieval history.",
  "Explain the concept of golang.",
  "Compare golang and cybersecurity.",
  "Why is fitness important?",
  "Compare social media and space travel.",
  "Why is space travel important?",
  "Tell me a joke about blockchain.",
  "How can I learn more about cybersecurity?",
  "Tell me a joke about neural networks.",
  "Give me a summary of social media.",
  "How can I learn more about medieval history?",
  "How can I learn more about philosophy?",
  "What are the benefits of Shakespeare?",
  "Give me a summary of Docker.",
  "What are the benefits of cybersecurity?",
  "Give me a summary of nutrition.",
  "How does data privacy work?",
  "Tell me a joke about cooking.",
  "Compare Docker and the stock market.",
  "Explain the concept of golang.",
  "Compare the stock market and AI.",
  "What is the history of fitness?",
  "What is the history of nutrition?",
  "Compare machine learning and artificial general intelligence.",
  "Write a story about a Python programming.",
  "What are the benefits of artificial general intelligence?",
  "Tell me a joke about medieval history.",
  "Write a story about a Python programming.",
  "How can I learn more about social media?",
  "Compare space travel and blockchain.",
  "Compare data privacy and medieval history.",
  "Compare Python programming and music theory.",
  "What is the history of data privacy?",
  "How does Shakespeare work?",
  "How does cybersecurity work?",
  "Compare nutrition and cybersecurity.",
  "Compare football and quantum mechanics.",
  "Tell me a joke about quantum mechanics.",
  "Give me a summary of data privacy.",
  "Give me a summary of golang.",
  "What is the history of machine learning?",
  "Give me a summary of blockchain.",
  "Why is music theory important?",
  "Compare philosophy and social media.",
  "Why is quantum mechanics important?",
  "Compare neural networks and football.",
  "Explain the concept of Kubernetes.",
  "Why is music theory important?",
  "Why is football important?",
  "How does data privacy work?",
  "Give me a summary of the stock market.",
  "Tell me a joke about medieval history.",
  "Write a story about a social media.",
  "What are the benefits of medieval history?",
  "Explain the concept of philosophy.",
  "How can I learn more about AI?",
  "How can I learn more about nutrition?",
  "Write a story about a fitness.",
  "Compare neural networks and climate change.",
  "What are the benefits of AI?",
  "Compare space travel and nutrition.",
  "What is the history of fitness?",
  "Write a story about a golang.",
  "How does climate change work?",
  "What are the benefits of Docker?",
  "What is the history of Kubernetes?",
  "Why is philosophy important?",
  "Compare space travel and neural networks."
];

export default function () {
  const prompt = prompts[Math.floor(Math.random() * prompts.length)];
  const payload = JSON.stringify({
    model: model,
    prompt: prompt,
    max_tokens: 100,
    temperature: 0
  });
  const params = { headers: { 'Content-Type': 'application/json' } };
  http.post(url, payload, params);
  sleep(1);
}